### ISSUE TITLE
Add a style to the Recordings Screen page (Do this after Updating Local Video Card)

### ISSUE THREAD

**Issue by canaleal** [DashboardCameraCapstoneTeam/EXPO-Advanced-Mobile-Dashcam#17]
The Recordings Screen page has a bunch of cards for each style. Unfortunately, these cards take up too much room.

At the top of each card group there should be a Date and Time followed by the thumbnails of each video. 

Example:

2022-10-25
[Image] [Image] [Image]

2022-10-16
[Image] [Image] [Image]

We need the Recordings Screen page to look like this:

![image](https://user-images.githubusercontent.com/49886351/200123517-87c3bc04-c1fa-440f-84e5-4afd215bc26c.png)

**Comment by jasminja13** [comment]
Fixed
